### ISSUE TITLE
InvalidOperationException on supplying '-r' multiple times

### ISSUE THREAD

**Issue by JonathanHUnity** [Unity-Technologies/unityscript2csharp#2]
Repro:
* .\tool\UnityScript2CSharp.exe -p .\USTest\ -u "C:\Program Files\Unity 2017.2.0b6" -r "D:\scratchpad\US\USTest\Assets\uniSWF\DLLs\LibUniSWF.dll" -r "D:\scratchpad\US\USTest\Assets\uniSWF\DLLs\LibUniSWFInternal.dll"

Expected: If this is not supported, print the help message.
Actual:

`Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at CommandLine.Core.OptionMapper.<>c__DisplayClassa.<MapValues>b__0(SpecificationProperty pt)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__58`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at CommandLine.Core.ReflectionExtensions.SetProperties[T](T instance, IEnumerable`1 specProps, Func`2 predicate, Func`2 selector)
   at CommandLine.Core.InstanceBuilder.Build[T](Func`1 factory, Func`3 tokenizer, IEnumerable`1 arguments, StringComparer nameComparer, CultureInfo parsingCulture)
   at CommandLine.Parser.<>c__DisplayClass4`1.<ParseArguments>b__2()
   at CommandLine.Parser.MakeParserResult[T](Func`1 parseFunc, ParserSettings settings)
   at CommandLine.Parser.ParseArguments[T](Func`1 factory, String[] args)
   at CommandLine.Parser.ParseArguments[T](String[] args)
   at UnityScript2CSharp.Program.Main(String[] args) in M:\Work\Repo\UnityScript2CSharp\UnityScript2CSharp\Program.cs:line 16`

**Comment by adrianoc-unity3d** [comment]
Fixed
