### ISSUE TITLE
Conversion fails for function with "System.Type" parameter

### ISSUE THREAD

**Issue by JonathanHUnity** [Unity-Technologies/unityscript2csharp#3]
Repro:
* Add the following code to a .js file:
`/** Register Exported class name widget class.
 */
function registerClass( exportName:String, widgetClass:System.Type ) {    
}`
* Run converter on the project

Expected: Succeeds without errors
Actual: Generates correct code, but gives the error "Cannot find assembly: 'System'"

Full -v error

 Cannot find assembly: 'System'

System.ApplicationException: Cannot find assembly: 'System'
   at Boo.Lang.Compiler.CompilerParameters.LoadAssemblyFromLibPaths(String assembly, Boolean throwOnError)
   at Boo.Lang.Compiler.CompilerParameters.ForName(String assembly, Boolean throwOnError)
   at Boo.Lang.Compiler.CompilerParameters.LoadDefaultReferences()
   at Boo.Lang.Compiler.CompilerParameters..ctor(IReflectionTypeSystemProvider reflectionProvider, Boolean loadDefaultReferences)
   at UnityScript.UnityScriptCompilerParameters..ctor(IReflectionTypeSystemProvider reflectionTypeSystemProvider, Boolean loadDefaultReferences)
   at UnityScript.UnityScriptCompilerParameters..ctor(Boolean loadDefaultReferences)
   at UnityScript.UnityScriptCompilerParameters..ctor()
   at UnityScript.UnityScriptCompiler..ctor()
   at UnityScript2CSharp.UnityScript2CSharpConverter.CreatAndInitializeCompiler(IEnumerable`1 inputs, IEnumerable`1 definedSymbols, IEnumerable`1 referencedAssemblies) in M:\Work\Repo\UnityScript2CSharp\UnityScript2CSharp\UnityScript2CSharpConverter.cs:line 68
   at UnityScript2CSharp.UnityScript2CSharpConverter.Convert(IEnumerable`1 inputs, IEnumerable`1 definedSymbols, IEnumerable`1 referencedAssemblies, Action`3 onScriptConverted) in M:\Work\Repo\UnityScript2CSharp\UnityScript2CSharp\UnityScript2CSharpConverter.cs:line 28
   at UnityScript2CSharp.Program.ConvertScripts(String scriptType, IList`1 scripts, UnityScript2CSharpConverter converter, IEnumerable`1 references, CommandLineArguments args, List`1 referencedSymbols) in M:\Work\Repo\UnityScript2CSharp\UnityScript2CSharp\Program.cs:line 174
   at UnityScript2CSharp.Program.Main(String[] args) in M:\Work\Repo\UnityScript2CSharp\UnityScript2CSharp\Program.cs:line 54

**Comment by JonathanHUnity** [comment]
Discovered while trying to convert uniSWF - Flash to Unity

**Comment by adrianoc-unity3d** [comment]
Fixed at 4d219b29bba5ddc8a49ff808fba40a7edc7efe2b
